"""add profilep

Revision ID: c802a7666d07
Revises: 0c4c0ccb8dda
Create Date: 2023-10-21 00:16:31.081326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c802a7666d07'
down_revision = '0c4c0ccb8dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profilepic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profilepic')

    # ### end Alembic commands ###
